blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostAllListView, PostUpdateView, PostDeleteView, PostCreateView

app_name = BlogConfig.name

urlpatterns = [
                  path('', PostListView.as_view(), name='post_list'),
                  path('post/list', PostAllListView.as_view(), name='post_all'),
                  path('post/<int:pk>/detail', PostDetailView.as_view(), name='post_detail'),
                  path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
                  path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
                  path('post/create', PostCreateView.as_view(), name='post_create'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path("mailing/", include('mailing.urls', namespace="mailing")),

                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, ClientListView, \
    ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView, toggle_activation, mailing_status

app_name = MailingConfig.name

urlpatterns = [
                  path('', MailingListView.as_view(), name='mailing_list'),
                  path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
                  path('mailing/create', MailingCreateView.as_view(), name='mailing_create'),
                  path('mailing/<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
                  path('mailing/<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
                  path('mailing/toggle/<int:mailing_id>/', toggle_activation, name='toggle_activation'),

                  path('message/list', MessageListView.as_view(), name='message_list'),
                  path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
                  path('message/create', MessageCreateView.as_view(), name='message_create'),
                  path('message/<int:pk>/update', MessageUpdateView.as_view(), name='message_update'),
                  path('message/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),

                  path('client/list', ClientListView.as_view(), name='client_list'),
                  path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
                  path('client/create', ClientCreateView.as_view(), name='client_create'),
                  path('client/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),
                  path('client/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),

                  path('mailing/status_list', mailing_status, name='mailing_status'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': False}


class Client(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(verbose_name="Электронной почты", unique=True)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.last_name} {self.first_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name="Тема сообщения")
    message = models.TextField(verbose_name="Сообщение")
    preview = models.ImageField(verbose_name="Превью", upload_to='message/preview', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания", **NULLABLE)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.title} от {self.created_at}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    class Periodicity(models.TextChoices):
        CUSTOM = 'C', 'Custom'
        DAILY = 'D', 'Ежедневно'
        WEEKLY = 'W', 'Еженедельно'
        MONTHLY = 'M', 'Ежемесячно'

    class Status(models.TextChoices):
        CREATED = 'C', 'Создана'
        RUNNING = 'R', 'Запущена'
        FINISHED = 'F', 'Завершена'

    title = models.CharField(max_length=100, verbose_name="Название рассылки")
    preview = models.ImageField(verbose_name="Превью", upload_to='mailing/preview', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Сообщение")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания", **NULLABLE)
    clients = models.ManyToManyField(Client, verbose_name="Список клиентов", blank=True)
    at_start = models.DateTimeField(verbose_name='Дата и время начала отправки')
    at_end = models.DateTimeField(verbose_name='Дата и время окончания отправки')
    periodicity = models.CharField(max_length=1, choices=Periodicity.choices, verbose_name='Периодичность')
    status = models.CharField(max_length=1, verbose_name="Статус рассылки", choices=Status.choices,
                              default=Status.CREATED)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=True, verbose_name="")

    def __str__(self):
        return f'Рассылка {self.pk}: {self.title} от {self.created_at},  периодичность - {self.periodicity}, количество клиентов - {self.clients.count()} чел. (статус - {self.status})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Attempt(models.Model):
    class Status(models.IntegerChoices):
        SUCCESS = 1, 'Успешно'
        FAILURE = 2, 'Неудачно'

    at_last_attempt = models.DateTimeField(verbose_name='Дата последней попытки', auto_now_add=True)
    status = models.SmallIntegerField(choices=Status.choices, verbose_name='Статус попытки')
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE, default="")
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts', verbose_name='попытки')

    def __str__(self):
        return f'Попытка отправки {self.mailing} от {self.at_last_attempt}'

    class Meta:
        ordering = ['-at_last_attempt']

mailing/forms.py
from django import forms
from django.forms import ModelForm

from mailing.models import Mailing, Client, Message


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'  # Включить все поля из модели Рассылки


class MailingCreateForm(ModelForm):
    class Meta:
        model = Mailing
        exclude = ['owner', 'is_active']


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ['owner']


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ['owner']

mailing/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import ClientForm, MessageForm, MailingCreateForm
from mailing.models import Mailing, Message, Client
from users.models import User


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            if self.request.user.groups.filter(name='manager').exists():
                # Возвращаем все рассылки
                return Mailing.objects.all()
            # Возвращаем только рассылки, принадлежащих текущему пользователю
            return Mailing.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Mailing.objects.none()


class MailingDetailView(DetailView):
    model = Mailing


def toggle_activation(request, mailing_id):
    mailing = Mailing.objects.get(pk=mailing_id)
    mailing.is_active = not mailing.is_active
    mailing.save()

    action = 'активирован' if mailing.is_active else 'деактивирован'
    messages.success(request, f'Пользователь {mailing.title} был {action}.')

    return redirect('mailing:mailing_detail', pk=mailing.id)  # Перенаправляем обратно в список пользователей


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingCreateForm

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Используем self.object.pk для получения первичного ключа обновленного объекта
        return reverse_lazy('mailing:mailing_detail', kwargs={'pk': self.object.pk})
        # ------------------ адрес куда перенаправить после совершения действия

    # def form_valid(self, form):
    #     # отправка созданной рассылки по почте при создании
    #     obj = form.save()
    #     send_mailing_email(obj)
    #     return super().form_valid(form)


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingCreateForm

    def get_success_url(self):
        return reverse_lazy('mailing:mailing_detail', kwargs={'pk': self.object.pk})


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


class MessageListView(ListView):
    model = Message

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            # Возвращаем только клиентов, принадлежащих текущему пользователю
            return Message.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Message.objects.none()


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Используйте self.object.pk для получения первичного ключа обновленного объекта
        return reverse_lazy('mailing:message_detail', kwargs={'pk': self.object.pk})


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse_lazy('mailing:message_detail', kwargs={'pk': self.object.pk})


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')


class ClientListView(ListView):
    model = Client

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            # Возвращаем только клиентов, принадлежащих текущему пользователю
            return Client.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Client.objects.none()


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Используйте self.object.pk для получения первичного ключа обновленного объекта
        return reverse_lazy('mailing:client_detail', kwargs={'pk': self.object.pk})


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse_lazy('mailing:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')


def mailing_status(request):
    mailings = Mailing.objects.prefetch_related('attempts').all()
    return render(request, 'mailing/mailing_status.html', {'mailings':mailings})

mailing/templates/mailing/client_confirm_delete.html
<link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal-default-theme.css"/>
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/remodal/remodal.js"></script>

<br><br><br>

<div class="remodal" data-remodal-id="modal" data-remodal-options="hashTracking: false, closeOnOutsideClick: false">
    <h1>Вы уверены, что хотите удалить этого клиента?</h1>
    <p>
        Пожалуйста, подтвердите, что вы хотите удалить данное клиента. Все связанные данные будут удалены.
    </p>
    <br>

    <form id="deleteForm" action="{% url 'mailing:client_delete' client.pk %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6">
                <button type="submit" class="btn btn-danger btn-block remodal-confirm">Подтвердить</button>
            </div>
            <div class="col-xs-6">
                <button id="closeButton" type="button" class="btn btn-default btn-block remodal-cancel">Закрыть</button>
            </div>
        </div>
    </form>
</div>

<script>
  $(document).ready(function () {
    var inst = $('[data-remodal-id=modal]').remodal();
    inst.open();

    // Redirect on close button click without deleting
    $('#closeButton').on('click', function () {
      window.location.href = "{% url 'mailing:client_list' %}"; // Redirect to mailing detail
    });
  });
</script>

mailing/templates/mailing/client_list.html
<title>Клиенты</title>

{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}



    <main class="container">
        <div class="row mb-2">
            <div class="d-grid gap-2 col-12 mx-auto">

                <table class="table">

                    <h4 class="mb-0 mt-3 mb-3 text-end">В списке {{ client_list.count }} {{ client_list.count | clients_word_form }}.</h4>

                    {% for client in client_list %}
                        <tbody>
                        <tr>
                            <td scope="row">
                                <a href="{% url 'mailing:client_detail' client.pk %}"
                                   class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                                    <img src="/media/client/client 002.jpg" alt="mdo" width="40" height="40"
                                         class="rounded-circle">
                                </a>
                            </td>
                            <td>{{ client.first_name }} {{ client.last_name }}</td>
                            <td>{{ client.email }}</td>
                            <td>{{ client.comment  | truncatechars:70 }}</td>
                            <td>
                                <div class="row">
                                    <a href="{% url 'mailing:client_update' client.pk %}" class="col"
                                       class="d-flex align-items-center text-dark text-decoration-none">
                                        <img src="/static/images/edit.jpg" alt="mdo" width="40" height="40"
                                             class="rounded-circle">
                                    </a>
                                    <a href="{% url 'mailing:client_delete' client.pk %}" class="col"
                                       class="d-flex align-items-center text-dark text-decoration-none">
                                        <img src="/static/images/delete.png" alt="mdo" width="40" height="40"
                                             class="rounded-circle">
                                    </a>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>

            </div>
        </div>
    </main>


{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
<link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal-default-theme.css"/>
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/remodal/remodal.js"></script>

<br><br><br>

<div class="remodal" data-remodal-id="modal" data-remodal-options="hashTracking: false, closeOnOutsideClick: false">
    <h1>Вы уверены, что хотите удалить рассылку?</h1>
    <p>
        Пожалуйста, подтвердите, что вы хотите удалить данную рассылку. Все связанные данные будут удалены.
    </p>
    <br>

    <form id="deleteForm" action="{% url 'mailing:mailing_delete' mailing.pk %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6">
                <button type="submit" class="btn btn-danger btn-block remodal-confirm">Подтвердить</button>
            </div>
            <div class="col-xs-6">
                <button id="closeButton" type="button" class="btn btn-default btn-block remodal-cancel">Закрыть</button>
            </div>
        </div>
    </form>
</div>

<script>
  $(document).ready(function () {
    var inst = $('[data-remodal-id=modal]').remodal();
    inst.open();

    // Redirect on close button click without deleting
    $('#closeButton').on('click', function () {
      window.location.href = "{% url 'mailing:mailing_detail' mailing.pk %}"; // Redirect to mailing detail
    });
  });
</script>

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}


    <main class="container">
        <div class="row mb-2">
            <div class="d-grid gap-2 col-8 mx-auto">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-lg h-md-250 position-relative bg-white">

                    <div class="d-grid gap-2 col-2 ms-4 mt-4">
                        {% if mailing.preview %}
                            <img src="{{ mailing.preview | media_filter }}" alt="mdo" width="120" height="120">
                        {% else %}
                            <img src="/media/mailing/preview/email.jpg" alt="mdo" width="120" height="120">
                        {% endif %}
                    </div>

                    <div class="col p-4 d-flex flex-column position-static">
                        <h2 class="mb-0 ms-3"><strong>{{ mailing.title }}</strong></h2>
                        <div class="mb-1 mb-4 text-body-secondary">от {{ mailing.created_at }}</div>
                        <h5 class="mb-0 mb-3"><strong>Тема
                            сообщения: </strong>{{ mailing.message.title | truncatechars:35 }}</h5>

                        <div class="row">
                            <div class="col-5" class="mb-1 text-body-secondary">Дата начала отправки:</div>
                            <div class="col" class="mb-1 text-body-secondary">{{ mailing.at_start }}</div>
                        </div>

                        <div class="row">
                            <div class="col-5" class="mb-1 text-body-secondary">Дата следующей отправки:</div>
                            <div class="col" class="mb-1 text-body-secondary">{{ current_datetime }}</div>
                        </div>

                        <div class="row mb-2">
                            <div class="col-5" class="mb-1 text-body-secondary">Дата окончания отправки:</div>
                            <div class="col" class="mb-1 text-body-secondary">{{ mailing.at_end }}</div>
                        </div>

                        <div class="row">
                            <div class="col-5" class="mb-1 text-body-secondary">Периодичность отправки:</div>
                            <div class="col" class="mb-1 text-body-secondary">{{ mailing.periodicity }}</div>
                        </div>

                        <div class="row">
                            <div class="col-5" class="mb-1 text-body-secondary">Статус рассылки:</div>
                            <div class="col" class="mb-1 text-body-secondary">{{ mailing.status }}</div>
                        </div>

                        <div class="col text-danger mt-2">
                            {% if not mailing.is_active and not perms.mailing.change_mailing %}
                                <strong>Рассылка отключена, обратитесь к администратору</strong>
                            {% endif %}
                        </div>

                        <h5 class="mb-0 mt-3 mb-1">В списке
                            рассылки {{ mailing.clients.count }} {{ mailing.clients.count | clients_word_form }}:</h5>
                        <ul>
                            {% for client in mailing.clients.all %}
                                <li>{{ client.first_name }} {{ client.last_name }}</li>
                                <!-- Adjust fields as necessary -->
                            {% empty %}
                                <li>Нет клиентов для этой рассылки.</li>
                            {% endfor %}
                        </ul>

                        <div class="d-grid gap-2 d-md-flex mt-5 justify-content-md-end">
                            {% if perms.mailing.change_mailing %}

                                {% if mailing.is_active %}
                                    <a class="btn btn-success" href="{% url 'mailing:toggle_activation' mailing.pk %}"
                                   role="button" style="width: 130px;">Отключить</a>
                                {% else %}
                                    <a class="btn btn-danger" href="{% url 'mailing:toggle_activation' mailing.pk %}"
                                   role="button" style="width: 130px;">Включить</a>
                                {% endif %}

                            {% endif %}

                            {% if mailing.owner == user %}
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_update' mailing.pk %}"
                                   role="button" style="width: 130px;">Редактировать</a>
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_delete' mailing.pk %}"
                                   role="button" style="width: 130px;">Удалить</a>
                            {% endif %}

                            <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}" role="button"
                               style="width: 130px;">Назад</a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </main>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}

    <!-- Блок рассылок -->
    {% for mailing in mailing_list %}
        <main class="container">
            <div class="row mb-2">
                <div class="col-md-12">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-0 shadow-lg h-md-250 position-relative bg-white">

                        <div class="col-2 ms-1 mt-1 mb-1 d-none d-lg-block">
                            {% if mailing.preview %}
                                <img src="{{ mailing.preview | media_filter }}" alt="mdo" width="200" height="200">
                            {% else %}
                                <img src="/media/mailing/preview/email.jpg" alt="mdo" width="200" height="200">
                            {% endif %}
                        </div>

                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-success-emphasis">{{ mailing.message.title }}</strong>
                            <h3 class="mb-0"><strong>{{ mailing.title }}</strong></h3>

                            <div class="mb-1 text-body-secondary">{{ mailing.created_at }}</div>
                            <h4 class="mb-auto">{{ mailing.message.message | truncatechars:50 }}</h4>
                            <hr>
                            <div class="row">
                                <div class="col" class="mb-1 text-body-secondary">Периодичность
                                    отправки: {{ mailing.periodicity }}</div>
                                <div class="col" class="mb-1 text-body-secondary">Статус: {{ mailing.status }}</div>
                                <div class="col text-danger">
                                    {% if not mailing.is_active %}
                                        <strong>Рассылка отключена, обратитесь к администратору</strong>
                                    {% endif %}
                                </div>
                            </div>

                            <a href="{% url 'mailing:mailing_detail' mailing.pk %}"
                               class="icon-link gap-1 icon-link-hover stretched-link"></a>
                        </div>

                    </div>
                </div>
            </div>
        </main>


    {% endfor %}

        <a class="btn btn-primary" href="{% url 'mailing:mailing_status' %}"
                                   role="button" style="width: 130px;">Отчёт</a>

{% endblock %}

mailing/templates/mailing/mailing_status.html
<title>Статусы рассылок</title>

{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}

    <body>
    <h1>Статусы рассылок</h1>
    <table>
        <thead>
        <tr>
            <th>Название рассылки</th>
            <th>Статус</th>
            <th>Попытки</th>
        </tr>
        </thead>
        <tbody>
        {% for mailing in mailings %}
            <tr>
                <td>{{ mailing.title }}</td>
                <td>{{ mailing.get_status_display }}</td>
                <td>
                    <ul>
                        {% for attempt in mailing.attempts.all %}
                            <li>{{ attempt.at_last_attempt }}
                                - {{ attempt.get_statu_display }}: {{ attempt.server_response }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </body>

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
<link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal-default-theme.css"/>
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/remodal/remodal.js"></script>

<br><br><br>

<div class="remodal" data-remodal-id="modal" data-remodal-options="hashTracking: false, closeOnOutsideClick: false">
    <h1>Вы уверены, что хотите удалить это сообщение?</h1>
    <p>
        Пожалуйста, подтвердите, что вы хотите удалить данное сообщение. Все связанные данные будут удалены.
    </p>
    <br>

    <form id="deleteForm" action="{% url 'mailing:message_delete' message.pk %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6">
                <button type="submit" class="btn btn-danger btn-block remodal-confirm">Подтвердить</button>
            </div>
            <div class="col-xs-6">
                <button id="closeButton" type="button" class="btn btn-default btn-block remodal-cancel">Закрыть</button>
            </div>
        </div>
    </form>
</div>

<script>
  $(document).ready(function () {
    var inst = $('[data-remodal-id=modal]').remodal();
    inst.open();

    // Redirect on close button click without deleting
    $('#closeButton').on('click', function () {
      window.location.href = "{% url 'mailing:message_detail' message.pk %}"; // Redirect to mailing detail
    });
  });
</script>

mailing/templates/mailing/message_detail.html
{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}


    <main class="container">
        <div class="row mb-2">
            <div class="d-grid gap-2 col-8 mx-auto">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-lg h-md-250 position-relative bg-white">

                    <div class="d-grid gap-2 col-2 ms-4 mt-4">
                        {% if message.preview %}
                            <img src="{{ message.preview | media_filter }}" alt="mdo" width="120" height="120">
                        {% else %}
                            <img src="/media/message/preview/email.jpg" alt="mdo" width="120" height="120">
                        {% endif %}
                    </div>

                    <div class="col p-4 d-flex flex-column position-static">
                        <h2 class="mb-0 ms-3"><strong>{{ message.title }}</strong></h2>
                        <div class="mb-1 mb-4 text-body-secondary">от {{ message.created_at }}</div>
                        <h5 class="mb-0 mb-1"><strong>Текст сообщения:</strong></h5>
                        <h5 class="mb-0 mb-3">{{ message.message }}</h5>




                        <div class="d-grid gap-2 d-md-flex mt-5 justify-content-md-end">
                            <a class="btn btn-primary" href="{% url 'mailing:message_update' message.pk %}" role="button"
                               style="width: 130px;">Редактировать</a>
                            <a class="btn btn-primary" href="{% url 'mailing:message_delete' message.pk %}" role="button"
                               style="width: 130px;">Удалить</a>
                            <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button"
                               style="width: 130px;">Назад</a>
{#                        </div>#}

                    </div>

                </div>
            </div>
        </div>
    </main>

{% endblock %}