blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostAllListView, PostUpdateView, PostDeleteView, PostCreateView

app_name = BlogConfig.name

urlpatterns = [
                  path('', PostListView.as_view(), name='post_list'),
                  path('post/list', PostAllListView.as_view(), name='post_all'),
                  path('post/<int:pk>/detail', PostDetailView.as_view(), name='post_detail'),
                  path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
                  path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
                  path('post/create', PostCreateView.as_view(), name='post_create'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path("mailing/", include('mailing.urls', namespace="mailing")),

                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': False}


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Статья')
    preview = models.ImageField(upload_to="blog/post_preview", verbose_name="Превью", **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата публикации")
    number_of_views = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")
    is_published = models.BooleanField(default=False, verbose_name="Добавить к избранным")

    def __str__(self):
        return f'{self.title} от {self.created_at} ({self.is_published})'




    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/forms.py
from django.forms import ModelForm, BooleanField

from blog.models import Post


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-class'


class PostForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Post
        exclude = ['number_of_views']

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView

from blog.forms import PostForm
from blog.models import Post
from services import get_data_from_cache


class PostListView(ListView):
    model = Post
    template_name = 'post/post_list.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return get_data_from_cache(Post)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_post'] = Post.objects.all()[:6]
        # последний пост
        context['latest_post'] = Post.objects.order_by('-created_at').first()
        # два избранных поста
        context['featured_posts'] = Post.objects.filter(is_published=True)[:2]
        return context


class PostAllListView(ListView):
    model = Post
    template_name = 'post/post_all.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'post/post_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'post/post_form.html'

    def get_success_url(self):
        return reverse_lazy('blog:post_update', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.number_of_views > 1:
            self.object.number_of_views -= 1
            self.object.save()
        return self.object


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post/post_confirm_delete.html'
    success_url = reverse_lazy('blog:post_all')


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post/post_form.html'

    def get_success_url(self):
        return reverse_lazy('blog:post_all')

blog/templates/post/post_all.html
<title>Список статей</title>

{% extends 'mailing/index.html' %}
{% load blog_tags %}
{% block content %}


    <main class="container">

        <!-- Раздел горячих новостей -->
        <div class="row g-5">
            <div class="col-md-12">
                <div class="position-sticky" style="top: 2rem;">
                    <a class="btn back-button btn-primary" href="{% url 'blog:post_list' %}" role="button" style="width: 130px;">Назад</a>

                    <!-- Раздел списка постов -->
                    <div>
                        <h1 class="fst-italic">Список постов</h1>
                        <ul class="list-unstyled">
                            {% for post in post_list %}
                                <li>
                                    <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
                                       href="{% url 'blog:post_detail' post.id %}">

                                        {% if post.preview %}
                                            <img src="{{ post.preview | media_filter }}" alt="mdo" width="100"
                                                 height="100">
                                        {% else %}
                                            <img src="/static/images/post.png" alt="mdo" width="100"
                                                 height="100">
                                        {% endif %}

                                        <div class="col-lg-11">
                                            <h6 class="mb-0">{{ post.title }}</h6>
                                            <small class="text-body-secondary">{{ post.created_at }}</small>
                                            <h6 class="text-body-secondary" ALIGN="justify">{{ post.content|truncatewords:30 }}</h6>

                                            <p style="color: black; margin: 0;"><strong>{{ post.number_of_views }}&#x1F441;</strong></p>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

blog/templates/post/post_confirm_delete.html
<link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal.css"/>
<link type="text/css" rel="stylesheet" href="https://bootstraptema.ru/plugins/2016/remodal/remodal-default-theme.css"/>
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2016/remodal/remodal.js"></script>

<br><br><br>

<div class="remodal" data-remodal-id="modal" data-remodal-options="hashTracking: false, closeOnOutsideClick: false">
    <h1>Вы уверены, что хотите удалить эту статью?</h1>
    <p>
        Пожалуйста, подтвердите, что вы хотите удалить данную статью. Все связанные данные будут удалены.
    </p>
    <br>

    <form id="deleteForm" action="{% url 'blog:post_delete' post.pk %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-xs-6">
                <button type="submit" class="btn btn-danger btn-block remodal-confirm">Подтвердить</button>
            </div>
            <div class="col-xs-6">
                <button id="closeButton" type="button" class="btn btn-default btn-block remodal-cancel">Закрыть</button>
            </div>
        </div>
    </form>
</div>

<script>
  $(document).ready(function () {
    var inst = $('[data-remodal-id=modal]').remodal();
    inst.open();

    // Redirect on close button click without deleting
    $('#closeButton').on('click', function () {
      window.location.href = "{% url 'blog:post_all' %}";
    });
  });
</script>

blog/templates/post/post_detail.html
{% extends 'mailing/index.html' %}
{% load blog_tags %}
{% block content %}

    <div class="container px-4 py-5" id="custom-cards">

        <div class="btn-group back-button" role="group" aria-label="Button group with nested dropdown">
        <a class="btn btn-primary" href="{% url 'blog:post_all' %}" role="button" style="width: 130px;">Назад</a>

            {% if perms.blog.change_post %}
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Действие
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'blog:post_update' post.pk %}">Редактировать</a></li>
                    <li><a class="dropdown-item" href="{% url 'blog:post_delete' post.pk %}">Удалить</a></li>
                </ul>
            </div>
            {% endif %}

        </div>

        <h1 class="text-secondary-color"><strong>{{ post.title }}</strong></h1>

        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg"
                 style="background-image:
                         {% if post.preview %}
                             url('{{ post.preview.url }}');
                         {% else %}
                             url('/static/images/post.png');
                         {% endif %}
                         background-size: cover;">
                <div class="card-body">
                    <div style="text-align: right;">
                        <div style="display: inline-block; background-color: white; border-radius: 8px; padding: 5px;">
                            <p style="color: black; margin: 0;"><strong>{{ post.number_of_views }}&#x1F441;</strong></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h3 class="text-secondary-color" style="text-align: justify;">
            <strong>{{ post.content }}</strong>
        </h3>
    </div>




{% endblock %}

blog/templates/post/post_form.html
<title>Статьи</title>

{% extends 'mailing/index.html' %}
{% load static %}
{% block content %}

    <main>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form class="row" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card">
                            <div class="card-body">
                                <div class="input-group mb-3">
                                    <span class="input-group-text" id="id_title"><strong>Заголовок</strong></span>
                                    <input type="text" class="form-control" name="title" value="{{ post.title }}"
                                           placeholder="Напишите заголовок"
                                           required id="id_title">
                                </div>

                                <label for="id_content"><strong>Статья:</strong></label>
                                <p>
                                    <textarea name="content" cols="169" rows="10" class="form-class" required
                                              id="id_content">{{ post.content }}</textarea>
                                </p>

                                <p>
                                    {% if post.preview %}
                                        <label for="id_preview"><strong>Превью:</strong></label>
                                        <a href="/media/{{ post.preview }}">{{ post.preview }}</a>
                                        <div>
                                            <input type="checkbox" name="preview-clear" id="preview-clear_id">
                                            <label for="preview-clear_id">Очистить</label><br>
                                        </div>
                                        <div class="col-auto d-none d-lg-block">
                                            <img src="{{ post.preview.url }}" width="100" height="100">
                                        </div>
                                        Изменить:
                                    {% endif %}
                                <input type="file" name="preview" accept="image/*" class="form-class"
                                       id="id_preview">
                                </p>

                                <p>
                                    <label for="id_is_published">Добавить к избранным:</label>
                                    <input type="checkbox" name="is_published" class="form-check-input"
                                           id="id_is_published"
                                            {% if post.is_published %} checked {% endif %}>
                                </p>

                                {% if object %}
                                    <button type="submit" class="btn btn-primary" role="button" style="width: 130px;">
                                        Сохранить
                                    </button>
                                    <a class="btn btn-primary" href="{% url 'blog:post_detail' post.id %}"
                                       role="button">Назад</a>
                                {% else %}
                                    <button type="submit" class="btn btn-primary" role="button" style="width: 130px;">
                                        Создать
                                    </button>
                                    <a class="btn btn-primary" href="{% url 'blog:post_all' %}"
                                       role="button">Отменить</a>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

blog/templates/post/post_form1.html
<title>Статьи</title>

{% extends 'mailing/index.html' %}
{% load static %}
{% block content %}


    <main>
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <form class="row" method="post" enctype="multipart/form-data">
                        <div class="card">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>

                            <div class="mt-3 mb-3">
                                <div class="col-lg-11">
                                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">

                                        <button type="submit" class="btn btn-primary" role="button"
                                                style="width: 130px;">
                                            {% if object %}
                                                Сохранить
                                            {% else %}
                                                Создать
                                            {% endif %}
                                        </button>
                                        {% if object %}
                                            <a class="btn btn-primary" href="{% url 'blog:post_detail' post.id %}"
                                               role="button">Отменить</a>
                                        {% else %}
                                            <a class="btn btn-primary" href="{% url 'blog:post_all' %}"
                                               role="button">Отменить</a>
                                        {% endif %}

                                    </div>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

blog/templates/post/post_list.html
<title>Статьи</title>

{% extends 'mailing/index.html' %}
{% load blog_tags %}
{% block content %}


    <main class="container">
        <!-- Раздел последнего поста -->
        <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
            <div class="col-lg-10 px-0">
                <h1 class="display-4 fst-italic">{{ latest_post.title }}</h1>
                <p class="lead my-3">{{ latest_post.content|truncatewords:30 }}</p>
                <p class="lead mb-0"><a href="{% url 'blog:post_detail' latest_post.id %}"
                                        class="text-body-emphasis fw-bold">Продолжить читать...</a></p>
            </div>
        </div>

        <!-- Раздел избранных постов -->
        <div class="row mb-2">
            <div class="row mb-2">
                {% for post in featured_posts %}
                    <div class="col-md-6">
                        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">
                                <h3 class="mb-0">{{ post.title }}</h3>
                                <div class="mb-1 text-body-secondary">{{ post.created_at }}</div>
                                <p class="card-text mb-auto">{{ post.content|truncatewords:6 }}</p>
                                <a href="{% url 'blog:post_detail' post.id %}"
                                   class="icon-link gap-1 icon-link-hover stretched-link">Читать...</a>
                            </div>
                            {% if post.preview %}
                                <div class="col-auto d-none d-lg-block">
                                    <img src="{{ post.preview.url }}" width="200" height="200">
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- Раздел горячих новостей -->
        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Горячие новости
                </h3>

                <article class="blog-post">
                    <h2 class="display-5 link-body-emphasis mb-1">Пример записи в блоге</h2>
                    <p class="blog-post-meta">January 1, 2021 by <a href="#">Mark</a></p>
                    <p>В этой записи блога показано несколько различных типов контента, поддерживаемых и стилизованных с
                        помощью Bootstrap. Базовая типографика, списки, таблицы, изображения, код и многое другое
                        поддерживаются, как и ожидалось.</p>

                    <hr>
                    <p>Это некий дополнительный контент-заполнитель абзаца. Он был написан, чтобы заполнить доступное
                        пространство и показать, как более длинный фрагмент текста влияет на окружающее содержимое. Мы
                        будем часто повторять его, чтобы демонстрация не прерывалась, поэтому будьте начеку, чтобы не
                        пропустить эту точно такую ​​же строку текста.</p>

                    <h2>Цитаты из блоков</h2>
                    <p>Это пример цитаты в действии:</p>
                    <blockquote class="blockquote">
                        <p>Цитируемый текст приводится здесь.</p>
                    </blockquote>
                    <p>Это некий дополнительный контент-заполнитель абзаца. Он был написан, чтобы заполнить доступное
                        пространство и показать, как более длинный фрагмент текста влияет на окружающее содержимое. Мы
                        будем часто повторять его, чтобы демонстрация не прерывалась, поэтому будьте начеку, чтобы не
                        пропустить эту точно такую ​​же строку текста.</p>
                </article>

                <article class="blog-post">
                    <h2 class="display-5 link-body-emphasis mb-1">Еще один пост в блоге</h2>
                    <p class="blog-post-meta">December 23, 2020 by <a href="#">Jacob</a></p>

                    <p>Это некий дополнительный контент-заполнитель абзаца. Он был написан, чтобы заполнить доступное
                        пространство и показать, как более длинный фрагмент текста влияет на окружающее содержимое. Мы
                        будем часто повторять его, чтобы демонстрация не прерывалась, поэтому будьте начеку, чтобы не
                        пропустить эту точно такую ​​же строку текста.</p>
                    <blockquote>
                        <p>Здесь можно привести более длинную цитату, возможно, с <strong>выделенным текстом</strong> в
                            середине.</p>
                    </blockquote>
                    <p>Это некий дополнительный контент-заполнитель абзаца. Он был написан, чтобы заполнить доступное
                        пространство и показать, как более длинный фрагмент текста влияет на окружающее содержимое. Мы
                        будем часто повторять его, чтобы демонстрация не прерывалась, поэтому будьте начеку, чтобы не
                        пропустить эту точно такую ​​же строку текста.</p>
                </article>
            </div>

            <!-- Раздел информации о блоге -->
            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-body-tertiary rounded">
                        <h4 class="fst-italic">О нас</h4>
                        <p class="mb-0">Настройте этот раздел, чтобы рассказать посетителям немного о вашем издании,
                            авторах, контенте или о чем-то совершенно другом. Полностью на ваше усмотрение.</p>
                    </div>

                    <!-- Раздел списка постов -->
                    <div>
                        <h4 class="fst-italic">Шесть последних постов</h4>
                        <ul class="list-unstyled">
                            {% for post in top_post %}
                                <li>
                                    <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
                                       href="{% url 'blog:post_detail' post.id %}">
                                        {% if post.preview %}
                                            <img src="{{ post.preview | media_filter }}" alt="mdo" width="100"
                                                 height="100">
                                        {% else %}
                                            <img src="/static/images/post.png" alt="mdo" width="100"
                                                 height="100">
                                        {% endif %}
                                        <div class="col-lg-8">
                                            <h6 class="mb-0">{{ post.title }}</h6>
                                            <small class="text-body-secondary">{{ post.created_at }}</small>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                            <a href="{% url 'blog:post_all' %}">Все новости...</a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </main>


{% endblock %}