blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostAllListView, PostUpdateView, PostDeleteView, PostCreateView

app_name = BlogConfig.name

urlpatterns = [
                  path('', PostListView.as_view(), name='post_list'),
                  path('post/list', PostAllListView.as_view(), name='post_all'),
                  path('post/<int:pk>/detail', PostDetailView.as_view(), name='post_detail'),
                  path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
                  path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
                  path('post/create', PostCreateView.as_view(), name='post_create'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path("mailing/", include('mailing.urls', namespace="mailing")),

                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, ClientListView, \
    ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView, toggle_activation, mailing_status

app_name = MailingConfig.name

urlpatterns = [
                  path('', MailingListView.as_view(), name='mailing_list'),
                  path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
                  path('mailing/create', MailingCreateView.as_view(), name='mailing_create'),
                  path('mailing/<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
                  path('mailing/<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
                  path('mailing/toggle/<int:mailing_id>/', toggle_activation, name='toggle_activation'),

                  path('message/list', MessageListView.as_view(), name='message_list'),
                  path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
                  path('message/create', MessageCreateView.as_view(), name='message_create'),
                  path('message/<int:pk>/update', MessageUpdateView.as_view(), name='message_update'),
                  path('message/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),

                  path('client/list', ClientListView.as_view(), name='client_list'),
                  path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
                  path('client/create', ClientCreateView.as_view(), name='client_create'),
                  path('client/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),
                  path('client/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),

                  path('mailing/status_list', mailing_status, name='mailing_status'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users import views
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, ProfileView, reset_password, user_list, toggle_activation

app_name = UsersConfig.name

urlpatterns = [
    path('', cache_page(60)(views.home), name='home'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),       # вход
    path('logout/', LogoutView.as_view(), name='logout'),                               # выход
    path('register/', RegisterView.as_view(), name='register'),                         # регистрация
    path('users/email-confirm/<str:token>/', email_verification, name='email-confirm'),     # верификация почты
    path('reset_password/', reset_password, name='reset_password'),                   # сброс и восстановление пароля
    path('profile/', ProfileView.as_view(), name='profile'),                          # редактирование профиля
    path('users/', user_list, name='user_list'),
    path('users/toggle/<int:user_id>/', toggle_activation, name='toggle_activation'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    first_name = models.CharField(max_length=50, verbose_name='Имя', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='phone number', **NULLABLE)
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='avatar', **NULLABLE)

    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f'{self.email} - {self.first_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import string

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from mailing.models import Mailing, Client
from blog.models import Post

import secrets


@login_required
def home(request):

    mailings = Mailing.objects.filter(owner=request.user)
    # Получение общего количества рассылок
    total_mailings = mailings.count()

    # Получение количества рассылок со статусом RUNNING
    running_mailings = mailings.filter(status='R').count()

    # Получение количества клиентов, принадлежащих текущему пользователю
    user_clients = Client.objects.filter(owner=request.user).count()

    # Получение трех случайных постов из модели Post
    random_posts = Post.objects.order_by('?')[:3]

    context = {
        'total_mailings': total_mailings,
        'running_mailings': running_mailings,
        'user_clients': user_clients,
        'random_posts': random_posts,
    }

    return render(request, 'users/main.html', context)  # Отображение main.html для авторизованных пользователей

def login_view(request):
    return render(request, 'users/login.html')  # Отображение login.html для неавторизованных пользователей


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()

        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}'

        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения почты перейдите по ссылке {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_random_password(length=8):
    """Генерирует случайный пароль."""
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(characters) for _ in range(length))


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = generate_random_password()
            user.password = make_password(new_password)  # Хэшируйте новый пароль
            user.save()

            # Send email with the new password
            send_mail(
                subject='Ваш новый пароль',
                message=f'Ваш новый пароль: {new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
            )

            messages.success(request, 'Новый пароль отправлен на ваш адрес электронной почты.')
            return redirect('users:login')  # Redirect to login page after successful reset

        except User.DoesNotExist:
            messages.error(request, 'Пользователь с таким адресом электронной почты не найден.')

    return render(request, 'users/reset_password.html')


def user_list(request):
    user = request.user
    if user.is_authenticated and user.groups.filter(name='manager').exists():
        users = User.objects.all()
        return render(request, 'users/user_list.html', {'users': users})
    raise PermissionDenied


def toggle_activation(request, user_id):
    user = User.objects.get(id=user_id)
    user.is_active = not user.is_active
    user.save()

    action = 'активирован' if user.is_active else 'деактивирован'
    messages.success(request, f'Пользователь {user.email} был {action}.')

    return redirect('users:user_list')  # Перенаправляем обратно в список пользователей

users/templates/users/login.html
{% extends 'mailing/index.html' %}
{% load static %}
{% block content %}


    <div class="modal modal-sheet position-static d-block p-4 py-md-0" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-4 shadow">
                <div class="modal-header p-5 pb-4 border-bottom-0">

                    <h1 class="fw-bold mb-0 fs-2">Вход в сервис</h1>

                </div>

                <div class="modal-body p-5 pt-0">
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control rounded-3" name="username" autofocus
                                   autocapitalize="none"
                                   autocomplete="username" maxlength="254" required id="id_username"
                                   placeholder="name@example.com">
                            <label for="id_username">Введите Email</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input type="password" class="form-control rounded-3" name="password" autofocus
                                   autocapitalize="none"
                                   autocomplete="username" maxlength="254" required id="id_password"
                                   placeholder="Password">
                            <label for="id_password">Введите пароль</label>
                        </div>

                        <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Войти</button>

                        <div class="d-flex justify-content-between mt-2">
                            <a class="rounded float-start" href="{% url 'users:register' %}">Зарегистрироваться</a>
                            <a class="rounded float-end" href="{% url 'users:reset_password' %}">Не помню пароль</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

users/templates/users/main.html
{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}


    <main class="container">

        <h2 class="text mb-4">{{ user.first_name }} - {{ user.email }}</h2>

        <div class="card text-center">

            <div class="card-header">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="{% url 'mailing:mailing_list' %}" class="btn-close"></a>
                </div>
            </div>

            <div class="card-body">
                <div class="row">
                    <h4 class="col" scope="row">Общее количество рассылок</h4>
                    <h4 class="col">{{ total_mailings }} {{ total_mailings | mailings_word_form }}</h4>
                </div>

                <div class="row">
                    <h4 class="col" scope="row">Количество активных рассылок</h4>
                    <h4 class="col">{{ running_mailings }} {{ total_mailings | mailings_word_form }}</h4>
                </div>

                <div class="row">
                    <h4 class="col" scope="row">Количество клиентов</h4>
                    <h4 class="col">{{ user_clients }}  {{ user_clients | clients_word_form }}</h4>
                </div>

                <!-- Раздел постов -->
                <div class="row">
                    <div class="row">
                        {% for post in random_posts %}
                            <div class="col-md-4 mt-4">
                                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                                    <div class="col-8 p-4 d-flex flex-column position-static">
                                        <h6 class="mb-0">{{ post.title }}</h6>
                                        <div class="mb-1 text-body-secondary">{{ post.created_at }}</div>
                                        <a href="{% url 'blog:post_detail' post.id %}"
                                           class="icon-link gap-1 icon-link-hover stretched-link">Читать...</a>
                                    </div>
                                    {% if post.preview %}
                                        <div class="col-auto d-none d-lg-block">
                                            <img src="{{ post.preview.url }}" width="130" height="130">
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="card-footer text-body-secondary">
                {% now 'd F Y' as current_date %}
                <p>Сегодня: {{ current_date|lower }} г. Время: {% now 'H:i:s' %}</p>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/index.html' %}
{% load static %}
{% block content %}


    <div class="modal modal-sheet position-static d-block p-4 py-md-0" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-4 shadow">
                <div class="modal-header p-5 pb-4 border-bottom-0">

                    <h1 class="fw-bold mb-0 fs-2">Регистрация</h1>

                </div>

                <div class="modal-body p-5 pt-0">
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-floating mb-3">
                            <input type="email" class="form-control rounded-3" name="email" autofocus
                                   maxlength="254" autofocus class="form-class" required id="id_email"
                                   placeholder="name@example.com">
                            <label for="id_email">Введите Email</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input type="password" class="form-control rounded-3" name="password1"
                                   autocomplete="new-password" class="form-class" required id="id_password1"
                                   placeholder="Password">
                            <label for="id_password">Введите пароль</label>
                        </div>

                        <span class="helptext">Для подтверждения введите пароль ещё раз.</span>

                        <div class="form-floating mt-1 mb-3">
                            <input type="password" class="form-control rounded-3" name="password2"
                                   autocomplete="new-password" class="form-class" required id="id_password2"
                                   placeholder="Password">
                            <label for="id_password2">Подтверждение пароля</label>
                        </div>
                            <span class="helptext">
                                <ul>
                                <li>Пароль не должен быть слишком похож на другую вашу личную информацию.</li>
                                <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                <li>Пароль не должен быть слишком простым и распространенным.</li>
                                <li>Пароль не может состоять только из цифр.</li>
                                </ul>
                            </span>


                        <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Зарегистрироваться
                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

users/templates/users/reset_password.html
{% extends 'mailing/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-4">
            <div class="card">

                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>

                <div class="card-body">
                    {% csrf_token %}
                    <label for="email">Введите ваш email:</label>
                    <input type="email" id="email" name="email" required>
                    <button type="submit">Восстановить пароль</button>


                    {% if messages %}
                    {% for message in messages %}
                    <div>{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                </div>

                <div class="card-footer"></div>

            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/index.html' %}
{% load static %}
{% block content %}


    <div class="modal modal-sheet position-static d-block p-4 py-md-0" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-4 shadow">

                <div class="modal-header p-5 pb-4 border-bottom-0">
                    <h1 class="fw-bold mb-0 fs-2">Профиль</h1>
                </div>

                <div class="modal-body p-5 pt-0">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}


                        <div class="form-floating mb-3">
                            <input type="email" class="form-control rounded-3" name="email" value={{ user.email }}
                                    maxlength="254" required id="id_username">
                            <label for="id_email">Email:</label>
                        </div>

                        <div class="form-floating mb-3">
                            <input type="text" class="form-control rounded-3" name="first_name"
                                   value={{ user.first_name }}
                                           maxlength="50" required id="id_first_name">
                            <label for="id_first_name">Имя:</label>
                        </div>


                        <div class="form-floating mb-3">
                            <input type="text" class="form-control rounded-3" name="phone" value={{ user.phone }}
                                    maxlength="35" required id="id_phone">
                            <label for="id_phone">Телефон:</label>
                        </div>

                        <p>
                            <label for="id_avatar">Avatar:
                                {% if user.avatar %}
                                    <div>
                                        На данный момент: <a href="/media/{{ user.avatar }}"><img src="/media/{{ user.avatar }}" alt="mdo" width="40" height="40"
                                         class="rounded-circle"></a>
                                    </div>
                                    <input type="checkbox" name="avatar-clear" id="avatar-clear_id">
                                    <label for="avatar-clear_id">Очистить</label><br>
                                {% else %}
                                    Отсутствует
                                {% endif %}
                            </label>

                        <div>
                            <input type="file" name="avatar" accept="image/*" id="id_avatar">
                            <input type="hidden" name="password" disabled id="id_password">
                        </div>
                        </p>

                        <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Сохранить</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form1.html
{% extends 'mailing/index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-4">
            <div class="card">

                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                </div>

                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>

                <div class="card-footer"></div>

            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
<title>Пользователи</title>

{% extends 'mailing/index.html' %}
{% load mailing_tags %}
{% block content %}

    <main class="container">
        <div class="row mb-2">
            <div class="d-grid gap-2 col-12 mx-auto">
                <h4 class="mb-0 mt-3 mb-3 text-end">В списке {{ users.count }} {{ users.count | users_word_form }}.</h4>

                {% if messages %}
                    {% for message in messages %}
                        <div>{{ message }}</div>
                    {% endfor %}
                {% endif %}

                <table class="table">

                    <thead>
                    <tr>
                        <th>Пользователь</th>
                        <th>Имя пользователя</th>
                        <th>Телефон</th>
                        <th>Статус</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td><h5 class="text-success">{{ user.email }}</h5></td>
                            <td><h5 class="text-success">{{ user.first_name }}</h5></td>
                            <td><h5 class="text-success">{{ user.phone }}</h5></td>

                            <td>{% if user.is_active %}
                                <h5 class="text-success">Active</h5>
                            {% else %}
                                <h5 class="text-danger">Inactive</h5>
                            {% endif %}
                            </td>

                            <td>
                                {% csrf_token %}
                                <a href="{% url 'users:toggle_activation' user.pk %}">
                                    <img src={% if user.is_active %} "/static/images/activated.png" {% else %}
                                        "/static/images/deactivated.png" {% endif %} width="70" height="30" class="rounded float-end"></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>

            </div>
        </div>
    </main>

{% endblock %}