blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostAllListView, PostUpdateView, PostDeleteView, PostCreateView

app_name = BlogConfig.name

urlpatterns = [
                  path('', PostListView.as_view(), name='post_list'),
                  path('post/list', PostAllListView.as_view(), name='post_all'),
                  path('post/<int:pk>/detail', PostDetailView.as_view(), name='post_detail'),
                  path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
                  path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
                  path('post/create', PostCreateView.as_view(), name='post_create'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path("mailing/", include('mailing.urls', namespace="mailing")),

                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, ClientListView, \
    ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView, toggle_activation, mailing_status

app_name = MailingConfig.name

urlpatterns = [
                  path('', MailingListView.as_view(), name='mailing_list'),
                  path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
                  path('mailing/create', MailingCreateView.as_view(), name='mailing_create'),
                  path('mailing/<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
                  path('mailing/<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
                  path('mailing/toggle/<int:mailing_id>/', toggle_activation, name='toggle_activation'),

                  path('message/list', MessageListView.as_view(), name='message_list'),
                  path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
                  path('message/create', MessageCreateView.as_view(), name='message_create'),
                  path('message/<int:pk>/update', MessageUpdateView.as_view(), name='message_update'),
                  path('message/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),

                  path('client/list', ClientListView.as_view(), name='client_list'),
                  path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
                  path('client/create', ClientCreateView.as_view(), name='client_create'),
                  path('client/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),
                  path('client/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),

                  path('mailing/status_list', mailing_status, name='mailing_status'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page

from users import views
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, ProfileView, reset_password, user_list, toggle_activation

app_name = UsersConfig.name

urlpatterns = [
    path('', cache_page(60)(views.home), name='home'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),       # вход
    path('logout/', LogoutView.as_view(), name='logout'),                               # выход
    path('register/', RegisterView.as_view(), name='register'),                         # регистрация
    path('users/email-confirm/<str:token>/', email_verification, name='email-confirm'),     # верификация почты
    path('reset_password/', reset_password, name='reset_password'),                   # сброс и восстановление пароля
    path('profile/', ProfileView.as_view(), name='profile'),                          # редактирование профиля
    path('users/', user_list, name='user_list'),
    path('users/toggle/<int:user_id>/', toggle_activation, name='toggle_activation'),

]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': False}


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Статья')
    preview = models.ImageField(upload_to="blog/post_preview", verbose_name="Превью", **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата публикации")
    number_of_views = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")
    is_published = models.BooleanField(default=False, verbose_name="Добавить к избранным")

    def __str__(self):
        return f'{self.title} от {self.created_at} ({self.is_published})'




    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': False}


class Client(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField(verbose_name="Электронной почты", unique=True)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.last_name} {self.first_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name="Тема сообщения")
    message = models.TextField(verbose_name="Сообщение")
    preview = models.ImageField(verbose_name="Превью", upload_to='message/preview', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания", **NULLABLE)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.title} от {self.created_at}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    class Periodicity(models.TextChoices):
        CUSTOM = 'C', 'Custom'
        DAILY = 'D', 'Ежедневно'
        WEEKLY = 'W', 'Еженедельно'
        MONTHLY = 'M', 'Ежемесячно'

    class Status(models.TextChoices):
        CREATED = 'C', 'Создана'
        RUNNING = 'R', 'Запущена'
        FINISHED = 'F', 'Завершена'

    title = models.CharField(max_length=100, verbose_name="Название рассылки")
    preview = models.ImageField(verbose_name="Превью", upload_to='mailing/preview', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Сообщение")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания", **NULLABLE)
    clients = models.ManyToManyField(Client, verbose_name="Список клиентов", blank=True)
    at_start = models.DateTimeField(verbose_name='Дата и время начала отправки')
    at_end = models.DateTimeField(verbose_name='Дата и время окончания отправки')
    periodicity = models.CharField(max_length=1, choices=Periodicity.choices, verbose_name='Периодичность')
    status = models.CharField(max_length=1, verbose_name="Статус рассылки", choices=Status.choices,
                              default=Status.CREATED)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=True, verbose_name="")

    def __str__(self):
        return f'Рассылка {self.pk}: {self.title} от {self.created_at},  периодичность - {self.periodicity}, количество клиентов - {self.clients.count()} чел. (статус - {self.status})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Attempt(models.Model):
    class Status(models.IntegerChoices):
        SUCCESS = 1, 'Успешно'
        FAILURE = 2, 'Неудачно'

    at_last_attempt = models.DateTimeField(verbose_name='Дата последней попытки', auto_now_add=True)
    status = models.SmallIntegerField(choices=Status.choices, verbose_name='Статус попытки')
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE, default="")
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts', verbose_name='попытки')

    def __str__(self):
        return f'Попытка отправки {self.mailing} от {self.at_last_attempt}'

    class Meta:
        ordering = ['-at_last_attempt']

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')
    first_name = models.CharField(max_length=50, verbose_name='Имя', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='phone number', **NULLABLE)
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='avatar', **NULLABLE)

    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return f'{self.email} - {self.first_name}'

mailing/forms.py
from django import forms
from django.forms import ModelForm

from mailing.models import Mailing, Client, Message


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'  # Включить все поля из модели Рассылки


class MailingCreateForm(ModelForm):
    class Meta:
        model = Mailing
        exclude = ['owner', 'is_active']


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ['owner']


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ['owner']

mailing/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import ClientForm, MessageForm, MailingCreateForm
from mailing.models import Mailing, Message, Client
from users.models import User


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            if self.request.user.groups.filter(name='manager').exists():
                # Возвращаем все рассылки
                return Mailing.objects.all()
            # Возвращаем только рассылки, принадлежащих текущему пользователю
            return Mailing.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Mailing.objects.none()


class MailingDetailView(DetailView):
    model = Mailing


def toggle_activation(request, mailing_id):
    mailing = Mailing.objects.get(pk=mailing_id)
    mailing.is_active = not mailing.is_active
    mailing.save()

    action = 'активирован' if mailing.is_active else 'деактивирован'
    messages.success(request, f'Пользователь {mailing.title} был {action}.')

    return redirect('mailing:mailing_detail', pk=mailing.id)  # Перенаправляем обратно в список пользователей


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingCreateForm

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Используем self.object.pk для получения первичного ключа обновленного объекта
        return reverse_lazy('mailing:mailing_detail', kwargs={'pk': self.object.pk})
        # ------------------ адрес куда перенаправить после совершения действия

    # def form_valid(self, form):
    #     # отправка созданной рассылки по почте при создании
    #     obj = form.save()
    #     send_mailing_email(obj)
    #     return super().form_valid(form)


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingCreateForm

    def get_success_url(self):
        return reverse_lazy('mailing:mailing_detail', kwargs={'pk': self.object.pk})


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


class MessageListView(ListView):
    model = Message

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            # Возвращаем только клиентов, принадлежащих текущему пользователю
            return Message.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Message.objects.none()


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Используйте self.object.pk для получения первичного ключа обновленного объекта
        return reverse_lazy('mailing:message_detail', kwargs={'pk': self.object.pk})


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse_lazy('mailing:message_detail', kwargs={'pk': self.object.pk})


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')


class ClientListView(ListView):
    model = Client

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            # Возвращаем только клиентов, принадлежащих текущему пользователю
            return Client.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Client.objects.none()


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Используйте self.object.pk для получения первичного ключа обновленного объекта
        return reverse_lazy('mailing:client_detail', kwargs={'pk': self.object.pk})


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse_lazy('mailing:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')


def mailing_status(request):
    mailings = Mailing.objects.prefetch_related('attempts').all()
    return render(request, 'mailing/mailing_status.html', {'mailings':mailings})

mailing/templates/mailing/includes/inc_footer.html
{% load static %}

<!-- Нижний колонтитул -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
        <div class="container">

            <div class="col-md-4 d-flex align-items-center">
                <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 - {% now 'Y' %} Company, Inc</span>
            </div>

        </div>
    </footer>

mailing/templates/mailing/includes/inc_menu.html
{% load static %}

<header class="p-3 mb-3 bg-dark border-bottom fixed-top">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'users:home' %}"
               class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <img src="{% static 'images/Hilshat76-Python-001.jpg' %}" alt="mdo" width="40" height="40"
                     class="rounded-circle">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <style>
                    .custom-link {
                        color: white;
                    }
                </style>

                <li><a href="{% url 'users:home' %}" class="nav-link px-2 custom-link">Главная</a></li>
                <li><a href="{% url 'mailing:mailing_list' %}" class="nav-link px-2 custom-link">Рассылки</a></li>
                <li><a href="{% url 'mailing:message_list' %}" class="nav-link px-2 custom-link">Сообщения</a></li>
                <li><a href="{% url 'mailing:client_list' %}" class="nav-link px-2 custom-link">Клиенты</a></li>
                <li><a href="{% url 'blog:post_list' %}" class="nav-link px-2 custom-link">Статьи</a></li>

                {% if perms.users.change_user %}
                    <li><a href="{% url 'users:user_list' %}" class="nav-link px-2 custom-link">Пользователи</a></li>
                {% endif %}

                {% if user.is_authenticated %}
                    {% if request.resolver_match.url_name == 'mailing_list' or request.resolver_match.url_name == 'mailing_detail' %}
                        <li><a href="{% url 'mailing:mailing_create' %}" class="nav-link ms-5 px-2 custom-link">Создать
                            рассылку</a></li>
                    {% elif request.resolver_match.url_name == 'message_list' or request.resolver_match.url_name == 'message_detail' %}
                        <li><a href="{% url 'mailing:message_create' %}" class="nav-link ms-5 px-2 custom-link">Создать
                            сообщение</a></li>
                    {% elif request.resolver_match.url_name == 'client_list' or request.resolver_match.url_name == 'client_detail' %}
                        <li><a href="{% url 'mailing:client_create' %}" class="nav-link ms-5 px-2 custom-link">Добавить
                            клиента</a></li>
                    {% endif %}

                    {% if perms.blog.change_post %}
                        {% if request.resolver_match.url_name == 'post_list' or request.resolver_match.url_name == 'post_detail' or request.resolver_match.url_name == 'post_all' %}
                            <li><a href="{% url 'blog:post_create' %}" class="nav-link ms-5 px-2 custom-link">Добавить статью</a></li>
                        {% endif %}
                    {% endif %}

                {% endif %}
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control" placeholder="Поиск..." aria-label="Search">
            </form>

            <div class="dropdown text-end">
                <a href="#" class="d-block custom-link text-decoration-none dropdown-toggle" id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.is_authenticated %}
                        {% if user.avatar %}
                            <img src="/media/{{ user.avatar }}" alt="mdo" width="40" height="40" class="rounded-circle">
                        {% else %}
                            <img src="/media/user/user.jpg" alt="mdo" width="40" height="40" class="rounded-circle">
                        {% endif %}
                    {% else %}
                        <img src="/media/user/user.jpg" alt="mdo" width="40" height="40" class="rounded-circle">
                    {% endif %}
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                    {% if user.is_authenticated %}
                        {% if user.is_authenticated %}
                            <h7 class="text-end m-2"><strong>{{ user.email }}</strong></h7>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'mailing:mailing_create' %}">Создать рассылки</a></li>
                        <li><a class="dropdown-item" href="{% url 'mailing:message_create' %}">Создать сообщение</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'mailing:client_create' %}">Добавить клиента</a></li>

                        {% if perms.blog.change_post %}
                        <li><a class="dropdown-item" href="{% url 'blog:post_create' %}">Добавить статью</a></li>
                        {% endif %}





                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>

                    {% else %}
                        <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</header>